name: Box Tests

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
        ocaml-compiler:
          - '4.08.0'
          - '4.13.x'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.ocaml-compiler }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
      - name: Install Opam dependencies
        run: opam install . --deps-only --with-test
      - name: Build OCaml
        run: opam exec -- dune build
      - name: Test OCaml
        run: opam exec -- dune runtest
