name: Box Tests

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - '4.08.0'
          - '4.13.x'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.ocaml-compiler }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
      - name: Install Opam dependencies
        run: opam install . --deps-only --with-test
      - name: Build OCaml
        run: opam exec -- dune build
      - name: Test OCaml
        if: "!( ${{ startsWith(matrix.os, 'ubuntu-') }} )"
        run: opam exec -- dune runtest
      - name: Test OCaml including timestamp tests
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: opam exec -- env BOX_TIMESTAMP_TESTS=true dune runtest
